booker/urls.py
from django.urls import path
from . import views

app_name = "booker"
urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("users.urls")),
    path('bbs/', include("booker.urls")),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.user_login, name="user_login"),
    path("process-login/", views.process_login, name="process_login"),
    path("sign-out/", views.sign_out, name="sign_out")
]

booker/models.py
from django.db import models
from users.models import CustomUser
from django.utils.timezone import datetime


class Driver(models.Model):
    STATUS = [
        ("A", "Available"),
        ("L", "Leave"),
        ("R", "On Road"),
    ]
    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    status = models.CharField(max_length=1, default="A", choices=STATUS)
    date_added = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.name


class Route(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    current_location = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)

    def __str__(self):
        return f"From: {self.current_location} ===> {self.destination}"


class Bus(models.Model):
    STATUS = [
        ("A", "Available"),
        ("F", "Faulty"),
        ("R", "On Road"),
    ]
    TYPES = [
        ("R", "Regular"),
        ("E", "Executive"),
    ]
    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    route = models.ForeignKey(Route, on_delete=models.SET_NULL, null=True, blank=True)
    driver = models.ForeignKey(Driver, on_delete=models.SET_NULL, null=True, blank=True)
    bus_number = models.CharField(max_length=10)
    capacity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, default="A", choices=STATUS)
    type = models.CharField(max_length=1, default="R", choices=TYPES)
    seat_price = models.DecimalField(max_digits=10, default=0.00, decimal_places=2)

    class Meta:
        verbose_name_plural = "Buses"

    def __str__(self):
        return f"Bus Number: {self.bus_number}"


class BusSeat(models.Model):
    STATUS = [
        ("B", "Booked"),
        ("U", "Not Booked"),
    ]
    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING)
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    seat_number = models.CharField(max_length=3)
    passenger_name = models.CharField(max_length=250, default="")
    passenger_phone = models.CharField(max_length=10, default="")
    status = models.CharField(max_length=1, default="U", choices=STATUS)
    time_booked = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name_plural = "Bus Seats"

    def __str__(self):
        return f"{self.bus.bus_number}::: Seat Number: {self.seat_number}"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.contrib.auth.models import Group
from zope.interface import named


class CustomUser(AbstractUser):
    ROLE = [
        (1, "Regular"),
        (2, "Administrator"),
    ]
    phone = models.CharField(max_length=10)
    role = models.PositiveSmallIntegerField(choices=ROLE, default=1)


@receiver(signal=post_save, sender=CustomUser)
def user_created(sender, instance, created, **kwargs):
    reg, created = Group.objects.get_or_create(name="Regular")
    admin, created = Group.objects.get_or_create(name="Administrator")
    if created:
        if instance.role == 1:
            print("Regular")
            reg.user_set.add(instance)
        else:
            print("Admin")
            admin.user_set.add(instance)
    else:
        if instance.role == 1:
            admin.user_set.remove(instance)
            reg.user_set.add(instance)
        else:
            reg.user_set.remove(instance)
            admin.user_set.add(instance)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = [
            'first_name', 'last_name', 'username', 'phone', 'password1', 'password2', 'role'
        ]


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = UserChangeForm.Meta.fields

booker/views.py
from django.shortcuts import render, redirect
from .models import Bus, Route, Driver, BusSeat
from django.contrib.auth.models import Group
from django.utils.timezone import datetime


def admin_dashboard(request):
    all_buses = Bus.objects.filter(date_added__date=datetime.now().date())
    bus_on_road = len([bus for bus in all_buses if bus.status == "R"])
    bus_not_on_road = len([bus for bus in all_buses if bus.status == "A"])
    faulty_buses = len([bus for bus in all_buses if bus.status == "F"])
    all_drivers = Driver.objects.filter(date_added__date=datetime.now().date())
    drivers_on_road = len([driver for driver in all_drivers if driver.status == "R"])
    drivers_on_leave = len([driver for driver in all_drivers if driver.status == "L"])
    drivers_not_on_road = len([driver for driver in all_drivers if driver.status == "A"])
    ctx = {
        'buses': all_buses, 'bor': bus_on_road,
        "bnor": bus_not_on_road, 'fb': faulty_buses,
        "drivers": all_drivers, 'dor': drivers_on_road,
        'dol': drivers_on_leave, 'dnor': drivers_not_on_road

    }
    return render(request, "booker/admin-dashboard/admin-dash.html", ctx)


def dashboard(request):
    reg = Group.objects.get(name="Regular")
    if request.user not in reg.user_set.all():
        return admin_dashboard(request)
    else:
        return render(request, "booker/regular/regular-dashboard.html")

users/views.py
from django.shortcuts import render, redirect
from .user_decorators import unauthenticated_user
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout


@unauthenticated_user
def user_login(request):
    return render(request, 'users/login.html')


def process_login(request):
    if request.method == "POST":
        uname = request.POST.get("uname")
        pwd = request.POST.get("pwd")
        try:
            auth_user = authenticate(username=uname, password=pwd)
        except Exception as e:
            messages.error(request, "Invalid Crendentials")
            return redirect("users:user_login")
        try:
            login(request, auth_user)
            return redirect("booker:dashboard")
        except Exception as e:
            messages.error(request, "Invalid Crendentials")
            return redirect("users:user_login")

    return HttpResponse("Glass Nkoaa!!!")


def sign_out(request):
    logout(request)
    return redirect("users:user_login")

booker/templates/booker/admin-dashboard/admin-dash.html
{% extends 'site-base.html' %}

{% block title %}Admin Panel{% endblock %}

{% block content %}
    {% include 'includes/booker/navbar.inc.html' %}
    <section id="admin-dash-header" class="container">
        <h4 class="mt-3">Bus Data</h4>
        <hr>
        <div class="row cards-row">
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-pm">
                  <div class="card-body">
                    <h3 class="text-center card-title text-primary">
                        Buses Enrolled Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-primary display-4">
                          {{ buses.count }}
                      </h3>
                      <button type="button" class="btn btn-outline-primary btn-block" data-toggle="modal" data-target="#allBusesModal">
                          More Details
                        </button>
                  </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-ss">
                  <div class="card-body">
                      <h3 class="text-center card-title text-success">
                        Buses On Road Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-success display-4">
                          {{ bor }}
                      </h3>
                      <button type="button" class="btn btn-outline-success btn-block" data-toggle="modal" data-target="#allBusesModal">
                          More Details
                        </button>
                  </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-wn">
                  <div class="card-body">
                    <h3 class="text-center card-title text-warning">
                        Buses Not On Road Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-warning display-4">
                          {{ bnor }}
                      </h3>
                      <button type="button" class="btn btn-outline-warning btn-block" data-toggle="modal" data-target="#allBusesModal">
                          More Details
                        </button>
                  </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-dg">
                  <div class="card-body">
                    <h3 class="text-center card-title text-danger">
                        Buses With Fault Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-danger display-4">
                          {{ fb }}
                      </h3>
                      <button type="button" class="btn btn-outline-danger btn-block" data-toggle="modal" data-target="#allBusesModal">
                          More Details
                        </button>
                  </div>
                </div>
            </div>
        </div>
        <hr id="hr-1">
    <h4 class="mt-3">Driver Data</h4>
        <hr>
        <div class="row cards-row">
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-pm">
                  <div class="card-body">
                    <h3 class="text-center card-title text-primary">
                        Drivers Enrolled Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-primary display-4">
                          {{ drivers.count }}
                      </h3>
                  </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-ss">
                  <div class="card-body">
                      <h3 class="text-center card-title text-success">
                        Drivers On Trip Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-success display-4">
                          {{ dor }}
                      </h3>
                  </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-wn">
                  <div class="card-body">
                    <h3 class="text-center card-title text-warning">
                        Drivers Not On Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-warning display-4">
                          {{ dnor }}
                      </h3>
                  </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3">
                <div class="card box-dg">
                  <div class="card-body">
                    <h3 class="text-center card-title text-danger">
                        Drivers On Leave Today
                    </h3>
                      <hr>
                      <h3 class="text-center text-danger display-4">
                          {{ dol }}
                      </h3>
                  </div>
                </div>
            </div>
        </div>
    </section>
    {% include 'includes/admin-modals.inc.html' %}
{% endblock %}

{% block js %}

{% endblock %}

booker/templates/booker/regular/regular-dashboard.html
{% extends 'site-base.html' %}

{% block title %}User Panel{% endblock %}

{% block content %}
    <h3>Regular Panel</h3>
{% endblock %}

{% block js %}
    
{% endblock %}

booker/templates/includes/admin-modals.inc.html
<div class="modal fade" id="allBusesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLongTitle">All Buses Registered Today</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
            {% for bus in buses %}
                <li>{{ bus.driver.name }}</li>
            {% empty %}
                <li>
                    No Bus Registered Today !
                </li>
            {% endfor %}
        </ul>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

booker/templates/includes/booker/navbar.inc.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-me">
  <div class="container">
    <a class="navbar-brand" href="#">
        <img src="{% static 'img/alpa-logo.png' %}" alt="" height="40vh" width="40vw"> AlphaCorp BBS
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        |+++|
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="moreNavItems" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Manage
            </a>
            <div class="dropdown-menu" aria-labelledby="moreNavItems">
              <a class="dropdown-item" href="#">Users</a>
              <a class="dropdown-item" href="#">Buses</a>
              <a class="dropdown-item" href="#">Drivers</a>
              <a class="dropdown-item" href="#">Finances</a>
            </div>
          </li>
            <li class="nav-item">
                <a href="#" class="nav-link">About Dev</a>
            </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="moreNavItems" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ request.user.username }}
            </a>
            <div class="dropdown-menu" aria-labelledby="moreNavItems">
              <a class="dropdown-item" href="#">Profile</a>
              <a class="dropdown-item" href="#">Reports</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item text-danger" href="#">Sign Out</a>
            </div>
        </ul>
      </div>
  </div>
</nav>

booker/templates/site-base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bus Booker | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {% block content %}{% endblock %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'site-base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <header id="login-header">
        <div class="container-fluid">
            <h3 class="text-center display-4 text-white pt-5 pb-4">
                <b>
                    Welcome to AlphaCorp BBS
                </b>
            </h3>
            <div class="row">
                <div class="offset-lg-4 col-sm-12 col-md-4 mb-5">
                    <div class="card bg-white text-dark">
                      <div class="card-body">
                        <h3 class="display-4 text-me text-center pb-4">
                            <b>
                                Sign In
                            </b>
                        </h3>
                          {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                  <strong>{{ message }}</strong> Please try again
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                            {% endfor %}

                          {% endif %}
                        <form method="POST" action="{% url 'users:process_login' %}">
                            {% csrf_token %}
                             <div class="form-group">
                                <label for="uname">Username</label>
                                <input type="text" class="form-control" id="uname" name="uname"  placeholder="Enter Username">
                              </div>
                              <div class="form-group">
                                <label for="pwd">Password</label>
                                <input type="password" class="form-control" id="pwd" name="pwd" placeholder="Password">
                              </div>
                              <button type="submit" class="btn bg-me btn-block shadow-sm">Grant Access</button>
                        </form>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block js %}

{% endblock %}